lib/supavisor_web/open_api_schemas.ex
The `PUT /api/tenants/{external_id}` controller method accepts a JSON body containing a partial tenant—excluding `id`, `external_id`, and timestamps—all wrapped in a `tenant` key.
External ID is obtained through a path parameter.
This change updates the definition of the body to match the controller implementation.
This PR updates documentation that lives within application code.
Currently, the documentation does not reflect the implemented behavior.
Add any other context or screenshots.
=> docs(openapi): match tenant update implementation

lib/supavisor.ex, lib/supavisor/client_handler.ex, lib/supavisor/db_handler.ex, lib/supavisor/manager.ex, lib/supavisor/monitoring/prom_ex.ex, lib/supavisor/monitoring/telem.ex, lib/supavisor/monitoring/tenant.ex, lib/supavisor/syn_handler.ex, lib/supavisor/tenant_supervisor.ex, lib/supavisor/tenants.ex, lib/supavisor/tenants/tenant.ex, lib/supavisor/tenants/user.ex, lib/supavisor_web/controllers/tenant_controller.ex, lib/supavisor_web/open_api_schemas.ex, lib/supavisor_web/views/tenant_view.ex, lib/supavisor_web/views/user_view.ex, priv/repo/migrations/20230125140723_create_tenants.exs, priv/repo/migrations/20230418151441_create_users.exs, priv/repo/seeds_after_migration.exs, test/integration/proxy_test.exs, test/supavisor/client_handler_test.exs, test/supavisor/db_handler_test.exs, test/supavisor/prom_ex_test.exs, test/supavisor/syn_handler_test.exs, test/supavisor/tenants_test.exs, test/supavisor_web/controllers/tenant_controller_test.exs, test/support/fixtures/tenants_fixtures.ex
This pull request introduces the capability to start multiple connection pools for tenants, organized by user entity.
Connection pools are identified using the pair `{tenant, db_user_alias}`.
The `db_user_alias` field serves as an alias for the `db_user` field, allowing for the creation of different types of pools (transaction/session/etc.) with the same Postgres user simultaneously.
A tenant can have many users, but the following combination for a user should be unique:
```elixir
[:db_user_alias, :tenant_external_id, :mode_type]
```
Supavisor retrieves the user name and tenant from the Postgres `username` field, which is divided by `.`. If a tenant has only one user, it is allowed to use just the tenant name in the username field, for example:
```bash …
```
=> Implement multiple pools per tenant

Makefile, config/config.exs, config/dev.exs, lib/supavisor.ex, lib/supavisor/client_handler.ex, lib/supavisor/db_handler.ex, lib/supavisor/manager.ex, lib/supavisor/tenant_supervisor.ex, lib/supavisor/tenants/user.ex, lib/supavisor_web/views/user_view.ex, priv/repo/migrations/20230502101623_add_timeout_to_users.exs, priv/repo/seeds_after_migration.exs, test/integration/proxy_test.exs
In this PR, session mode functionality is implemented, with each client connection initiating a direct link to the tenant's database. The primary work is done using poolboy's `max_overflow` parameter. 
For session mode, we start an empty pool and set a specific value for `max_overflow`, which represents the maximum number of workers created if the pool is empty.
=> Implement session mode functionality

dev/postgres/md5/etc/postgresql/pg_hba.conf, docker-compose.db.yml, lib/supavisor/db_handler.ex, test/supavisor/db_handler_test.exs
Allow tenants to authenticate using [MD5 method](https://www.postgresql.org/docs/current/auth-password.html).
Simply ignores `:authentication_md5_password` messages from server.
Handles `:authentication_md5_password` messages from server, proper replying the digested hash.
Based on [Postgrex implementation](https://github.com/elixir-ecto/postgrex/blob/v0.17.1/lib/postgrex/protocol.ex#L805-L812).
Currently working on local docker postgres instance and on private AWS RDS instance.
Available to improve the code and to generate unit tests and/or integration tests.
=> feat: handle MD5 authentication

lib/supavisor/client_handler.ex, lib/supavisor/helpers.ex, lib/supavisor/tenants.ex, lib/supavisor/tenants/tenant.ex, lib/supavisor_web/views/tenant_view.ex, priv/repo/migrations/20230718175315_add_sni_host.exs, test/supavisor/client_handler_test.exs
This PR introduces a new method to retrieve the tenant ID. If the client uses an SSL connection, we attempt to find the tenant by using `sni_hostname`
=> feat: retrieve the tenant id from the server name indication

lib/supavisor/client_handler.ex, lib/supavisor/db_handler.ex, lib/supavisor/manager.ex, lib/supavisor/protocol/client.ex, priv/repo/seeds_after_migration.exs, test/integration/proxy_test.exs
This PR introduces support for prepared named statements in transaction mode. 
[Supavisor attempts to decode all incoming queries](https://github.com/supabase/supavisor/blob/493c6deac161fa13780e54d8eeb8528ca9dd7965/lib/supavisor/client_handler.ex#L807) from connected users and retrieves the SQL statement by parsing the decoded queries through an [existing Rustler wrapper](https://github.com/supabase/supavisor/blob/feat/named_ps/native/pgparser/src/lib.rs) around `libpg_query`. When the parsed query contains `PrepareStmt` or `DeallocateStmt` (which requires removing an existing named statement), the `ClientHandler` [broadcasts](https://github.com/supabase/supavisor/blob/493c6deac161fa13780e54d8eeb8528ca9dd7965/lib/supavisor/client_handler.ex#L813-L825) it to all other `DbHandlers` in the …
=> feat: handling of named prepared statements

lib/supavisor/protocol/client.ex, lib/supavisor/protocol/server.ex
Improve decoding paths by optimising for some paths. Also, cut down needless
doubled iteration.
=> ft: improve decoding paths

lib/supavisor/client_handler.ex, lib/supavisor/db_handler.ex
Replace uses of `||` with `or` in cases where both sides of operator are for
sure boolean.
Reason for that is that `||` works on other values than boolean, which mean that
`a || b` is translated to:
```elixir
case a do
val when val in [nil, false] -> b
_ -> a
end
```
Which needs to perform more tests and cannot be optimised that easily by the
compiler. New code should be easier for compiler to optimise.
=> chore: use `or` instead of `||`

lib/supavisor/client_handler.ex
Performance fix
We traverse whole state each time we want to compute whether we want to enable
any timeouts. It causes measurable performance hit. As it is map and we know
only that there is only limited set of keys that can affect timeouts it is
better to access it directly.
Access only required fields. It also makes that function performance less
dependant on state size.
=> ft: do not traverse whole state for actions handling

lib/supavisor/monitoring/telem.ex, lib/supavisor/tenants_metrics.ex, test/supavisor/db_handler_test.exs
Performance improvement.
Metrics are gathered with normal priority. That can have performance impact on core of the application.
Lower priority of the metrics gathering process to not interfere with core of the application. This may cause some irregularities in gathered metrics, but at the same time it should reduce performance fluctuations of Supabase core.
=> ft: gather metrics with low priority

.github/workflows/elixir.yml
CI bug fix
Fetch PLT cache with relaxed key match.
=> chore: fetch PLT cache with relaxed key as well

lib/supavisor/application.ex, test/integration/proxy_test.exs, test/supavisor/prom_ex_test.exs, test/supavisor/syn_handler_test.exs, test/supavisor_web/controllers/metrics_controller_test.exs, test/support/cluster.ex, test/test_helper.exs
Replace deprecated `ct_slave` module with new `peer` module.
This also changes the sub-nodes to start only when needed instead of starting always for whole suite.
=> Move from `ct_slave` to `peer`

lib/supavisor/manager.ex
Current implementation calls `Access.get/2` twice. Instead of using
`Access.get/2` at all, we can use pattern matching.
=> chore: reduce `Access` calls

config/config.exs, config/dev.exs, lib/supavisor/application.ex, lib/supavisor/handler_helpers.ex, lib/supavisor/handlers/proxy/client.ex, lib/supavisor/handlers/proxy/db.ex, lib/supavisor/handlers/proxy/handler.ex, lib/supavisor/helpers.ex, lib/supavisor/monitoring/prom_ex.ex
The current PR introduces a new handler that will replace session mode. It authenticates incoming connections via auth queries, establishes a TCP connection to the tenant's database, and then simply forwards data between the client and the database, functioning primarily as a proxy
=> feat: implement proxy handler

flake.lock, flake.nix, nix/package.nix
Add [Nix Flake][nix-flake] with [Devenv][devenv] shell for development.
Currently it defines only development environment for Supavisor. In the future the plan is to add package definition as well as NixOS module to the Flake. This will simplify deployment on NixOS platforms as well as should help with spawning virtual machines with Supavisor running on them.
To use this shell you need to install [Nix][ds-installer] or [Lix][lix] and then you can use:
```sh
nix develop --impure
```
To start new Bash shell with all dependencies installed.
To run PostgreSQL you can use:
```sh
nix run .#up --impure
```
Which will create DB and run initialisation script. It will run it *natively*, not within Docker or other containerisation technology.
I am also working on [defining QEMU …
=> chore: add Nix Flake to project

flake.lock, lib/supavisor/client_handler.ex, lib/supavisor/manager.ex
- **chore: update Nix Flakes**
- **fix: some compilation warnings about unused stuff**
=> fix: cleanup warnings

.github/workflows/elixir.yml
This will raise if there are some pending changes to the `mix.lock`. This is to ensure, that `mix.lock` was uploaded after dependency changes.
=> chore: check if lockfile is up to date

test/supavisor/prom_ex_test.exs, test/test_helper.exs
That tests are constantly causing us problems in CI, but as it is test for internal functionality that do not affect users directly. So to streamline testing disable running these tests in default run. To run them one can use
mix test --include flaky
=> test: mark PromEx test as flaky

lib/supavisor/db_handler.ex
That will reduce amount of error logs related to unexpected process shutdown (as `db_termination` is rather expected shutdown).
=> fix: mark `:db_termination` as shutdown

lib/supavisor/db_handler.ex
Small fix to reduce noise during `DbHandler` exits.
It exits with abnormal reason, which causes noisy message to be printed in the log.
Exit with normal reason, which will print only our logs, no system logs.
=> fix: `DbHandler.stop/1` should exit with normal reason

lib/supavisor/client_handler.ex, lib/supavisor/db_handler.ex, lib/supavisor/protocol/server.ex
Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
=> chore: improve active_count

test/integration/external_test.exs, test/integration/js/postgres/index.js, test/integration/js/postgres/test.js
- **test: increase pool size in external test suite to match nano instances**
- **test: make timeouts configurable**
- **test: disable prepared transactions test, as these are disabled for security reasons**
- **test: disable cursor tests in transaction mode**
- **test: disable custom socket test**
- **test: disable MAX_PARAMETERS_EXCEEDED test**
- **test: disable query format errors test**
- **test: run connection reserving test only in session mode**
- **test: make Postgres.js more verbose**
- **test: ensure connections with different parameters are available where needed**
- **test: fix typo in test name**
=> test: update Postgres.js tests

lib/supavisor/client_handler.ex, lib/supavisor/handler_helpers.ex, lib/supavisor/protocol/server.ex, test/supavisor/protocol_test.exs
This allows us to use this piece of code in function head in pattern
match. This reduces places where the magic value is required and make
the code a little bit neater and cleaner.
=> feat: change `Protocol.Server.cancel_message/2` function a macro

lib/supavisor/monitoring/prom_ex.ex, test/integration/proxy_test.exs, test/supavisor/prom_ex_test.exs, test/support/fixtures/single_connection.ex
As we are depending on the undocumented internals of the Peep library, we accidentally were broken by recent update in Peep where they have added feature of stripped metrics storage. In this change there were no more named ETS tables and there may be more than one ETS table in case of striped tables. Now we are traversing all tables used by Peep to cleanup them all (even though we are currently using regular store, but this fix should work in case of striped tables as well).
=> fix: cleanup Peep metrics

test/integration/proxy_test.exs
This make test more flaky, is harmful to the test, and in general is bad practice.
=> test: do NOT trap exits in tests

lib/supavisor/client_handler.ex
- proxy ClientHandler should terminate when manager terminates
- needs tests
=> fix: always monitor the manager

lib/supavisor/monitoring/tenant.ex
Currently we measure pools checkouts in milliseconds, but these do not give us enough resolution and almost everything is crammed into `le="1"` bucket.
Change time unit used for measures to microsecond so all measurements are multiplied by factor of `1000` which should give us better insights into real distribution.
=> feat: use microseconds for measuring pool checkouts

lib/supavisor/client_handler.ex
This approach make data handling more concise and less prone to errors. This is also will make extraction of different working modes easier in the future refactoring.
=> chore: extract handling network data to separate function

lib/supavisor/monitoring/telem.ex, lib/supavisor/monitoring/tenant.ex
This partially reverts commit 4b498871ed54b726748d95808a2a840e8a51735c.
The change was not properly implementing previous behaviour in presence of multiple sockets reporting to the same set of attributes. Instead of summing their usage it was reporting only the latest one.
=> fix: properly compute socket usage

lib/supavisor/metrics_cleaner.ex
Switch to using Telemetry for reporting duration of cleanup. This should help with future observability.
=> feat: use Telemetry in MetricsCleaner

lib/supavisor/application.ex
To differentiate between different clusters we have added `LOCATION_KEY` which should denote different working cluster. If that variable is not set, then it defaults to `REGION` value.
=> feat: add `location_key` to global metadata

config/runtime.exs
It will fallback to `REGION` if there is no `LOCATION_ID`. It also adds support for `CLUSTER_ID` to specify the cluster independently of the above variables.
=> fix: use `LOCATION_ID` for cluster identification

config/config.exs, config/runtime.exs, flake.nix, lib/supavisor/tenants/tenant.ex, mix.exs, test/supavisor/monitoring/prom_ex_test.exs
- **chore: add more pre-commit checks**
- **feat: use built in JSON module for JSON parsing**
=> feat: use built in json module

lib/supavisor_web/open_api_schemas.ex
Bug fix - Corrects the OpenAPI schema definition by removing invalid required field specifications.
I used `swagger2openapi` to generate an OpenAPI yml from the swagger endpoint. The OpenAPI schema in `lib/supavisor_web/open_api_schemas.ex` incorrectly lists some fields as required that don't actually exist in the schema definition, which makes client side OpenAPI validation fail. 
The schema's required fields list has been updated to only include fields that actually exist in the schema definition.
=> Remove required fields from OpenAPI schema that don’t exist

.github/workflows/stage.yml
I'm getting an awkward dep resolution error in release_stage CI:
```
Resolving Hex dependencies...
Resolution completed in 0.518s
Unchanged:
artificery 0.4.3
backoff 1.1.6
...
syn 3.3.0
**telemetry 1.3.0** <-- 1.3.0 here
...
Dependencies have diverged:
* telemetry (Hex package)
the dependency telemetry 1.2.1 <-- where does this come from?
> In deps/finch/mix.exs:
{:telemetry, "~> 0.4 or ~> 1.0", [app_properties: [description: ~c"Dynamic dispatching library for metrics and instrumentations", vsn: ~c"1.2.1", registered: [], mod: {:telemetry_app, []}, applications: [:kernel, :stdlib], env: [], modules: [:telemetry, :telemetry_app, :telemetry_handler_table, :telemetry_sup, :telemetry_test], licenses: [~c"Apache-2.0"], links: [{~c"Github", ~c"https://github.com/beam-telemetry/telemetry"}], …
```
=> ci: clean up old release before getting deps, clean deps too

deploy/upgrade/staging.config
We have some clusters using v2.5.1 and some using v2.5.2, plus having issues building soft upgrades on CI, failing at deps stage. This doesn't seem to be new.
=> chore: hard deploy for v2.5.3 in staging

test/integration/postgres_switching_test.exs, test/test_helper.exs
`[include: [:integration], exclude: [:docker]]` runs tests with both tags (inclusion overrides exclusion). So we need to use a different tag.
=> test: change tags: integration + docker -> integration_docker

lib/supavisor/client_handler.ex, lib/supavisor/monitoring/tenant.ex, test/supavisor/monitoring/tenant_test.exs
Store start_time in client connection registry, then periodically emit telemetry for active client connections.
=> feat: add metric for client connection lifetime

lib/supavisor/application.ex, lib/supavisor/health.ex, lib/supavisor_web/controllers/tenant_controller.ex, lib/supavisor_web/open_api_schemas.ex, test/supavisor/health_test.exs, test/supavisor_web/controllers/tenant_controller_test.exs
Introduces `Supavisor.Health`, which provides a function that runs health checks.
Added two checks:
- Acceptable ERPC latencies: fails if a node has high latency to all other nodes through :erpc. Doesn't run if in a 1 or 2 node cluster. Fails if **all requests** have latency over 500ms or fail.
- Database reachable: fails if can't run a simple query in the database.
Calls this function on the health check endpoint, and return 503 if health checks are failing. After some time, if the condition persists, the infrastructure should restart the instance.
=> feat: check database and erpc capabilities on health check

lib/supavisor/client_handler.ex, lib/supavisor/protocol/server.ex, test/supavisor/protocol_test.exs
This PR enforces strict and explicit pattern matching by replacing the raw binary pattern `<<_::64>>` with the semantically meaningful `ssl_request_message` macro, reducing the risk of accidental matches and improving readability
=> feat: add ssl_request_message macro for pattern matching

lib/supavisor/monitoring/osmon.ex
The `ram_usage` metric doesn't give a good picture of the memory usage in the system, since it checks only free memory, not available memory.
=> feat: better OS memory metrics

lib/tasks/gen.appup.ex, mix.exs
This change allows us to write (and version) appups instead of using distillery to gen Supavisor's appups.
It's something that we may need in some cases, e.g.: the update from v2.0.21 to v2.1.x requires a few dependency bumps. If we write the appups for these dependencies, we can run a soft deploy.
**Whenever you can, use the auto-generated appup**, with `UPGRADE_FROM=x.y.z mix release`. When you can't, you may use manual appups:
1. Determine the supavisor version upgrade path. E.g.: `2.0.21-2.1.3`. Create a directory for this upgrade path on `relups`. Inside it, create an `appups` directory.
2. Generate the necessary appups with `mix supavisor.gen.appup`. For example, `mix supavisor.gen.appup --app=phoenix_live_view --from=0.20.17 --to=1.0.2 --path=relups/2.0.21-2.1.3/appups`. At this …
=> feat: support manually written appups

flake.nix
Explicitly list `libclang` dependency for the flake setup and configure the `LIBCLANG_PATH` variable to use that dependency for development using nix flake environment. I originally fixed it using `llvmPackages_16.libclang`, but it also works with `pkgs.libclang` so I am changing to this one in the last pushed commit.
=> chore: fix nix development environment missing libclang

lib/supavisor/application.ex, lib/supavisor/cache_refresh_limiter.ex, lib/supavisor/client_handler.ex, lib/supavisor/secret_checker.ex, test/integration/proxy_test.exs
- Fixes an issue where the first authn request after a credential change always would fail.
- Adds a cache refresh limit of 3 per minute per pool (triggered every time the password is wrong). Previosuly, limited to once every 15s. This is mostly due to tests. In tests, if we don't have this, the hard limit of once per 15s causes the test to flak.
- Adds an optimization where we use the existing SecretsChecker connection instead of opening a new one to refresh the cache.
=> fix(authn): when credential changes are detected, retry the auth request 

lib/supavisor_web/controllers/tenant_controller.ex, lib/supavisor_web/open_api_schemas.ex, lib/supavisor_web/views/user_view.ex, test/supavisor_web/controllers/tenant_controller_test.exs, test/support/conn_case.ex
Test improvements
- `TenantControllerTest` did not cover upstream TLS certificate validation (`upstream_tls_ca`, `upstream_verify`).
- Tests used `Routes.tenant_path/3` instead of `~p` verified routes.
- JSON responses were not validated against OpenAPI schemas.
- Added tests for upstream TLS CA handling (valid, invalid, and verify cases).
- Migrated tests to use `~p` verified routes.
- Added `assert_schema/2` checks for JSON responses.
=> test: add upstream TLS validation and schema assertions
